### ISSUE TITLE
CORS Issue?

### ISSUE THREAD

**Issue by lazmo88** [getshifter/wp-serverless-forms#13]
Hello, we tested the plugin with CF7 and for some reason submitting the form fails.

As per the console, it is due CORS issues? Is the problem with the plugin or with the endpoint?

Thank you for advising!

**Comment by lazmo88** [comment]
Update: The same issue with all tested endpoints, so assuming it is something to do with the plugin itself.

**Comment by emaildano** [comment]
Hey @lazmo88, there was a recent change in how Chrome (V8) handled CORS which broke a few things. The most recent version of WP Serverless Forms 1.3.1 resolved that and removed Axios so it should offer a speed improvement too!
